#!/usr/bin/env bash
# Install my load balancer

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 348631-web-01 52.86.81.27:80 check
    server 438863-web-02 52.91.125.237:80 check
"
apt-get -y update
apt-get -y upgrade

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

apt-get -y install haproxy
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
