#!/usr/bin/env bash
#doing several things just watch and learn

file= "/var/run/myscript.pid"

if [ ! -e "$file" ]; then
  touch "$file"
fi

sleep 2 &

echo $! > "$file"

out_handle()
{
echo "I hate the kill command"
rm "$file"
}

sigint_handle()
{
echo "Y U no love me?!"
}

trap out_handle SIGTERM SIGQUIT
trap sigint_handle SIGINT

while true; do
 echo "To infinity and beyond"
 sleep 2
 done

